### ISSUE TITLE
build errror

### ISSUE THREAD

**Issue by neolu** [peytonicmaster6/libcamera-apps-dual_camera#1]
/home/dev/works/libcamera-apps-dual_camera/image/jpeg.cpp:470:46: error: cannot convert ‘const libcamera::Control<int>’ to ‘unsigned int’
  470 |   if (metadata.contains(libcamera::controls::ExposureTime))
      |                         ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
      |                                              |
      |                                              const libcamera::Control<int>

**Comment by peyton-howe** [comment]
Fixed with most recent [commit](url=https://github.com/peytonicmaster6/libcamera-apps-dual_camera/commit/83d00c0776862e31c22a64641cbb773a6e463a19) to the newest libcamera-apps and libcamera support!
